create database UPWale_com;
use UPWale_com;
create table users(username varchar(15) PRIMARY KEY,email varchar(80),pass varchar(10));
create table products(id integer(4) PRIMARY KEY AUTO_INCREMENT,pname varchar(100),img1 varchar(200),img2 varchar(200),img3 varchar(200),img4 varchar(200),price decimal(7,2),brand varchar(30),ptype varchar(30),description varchar(1000));
insert into products values(01,'Boat bassHeads 225','images/boat/BOAT BASSHEADS 225-1.PNG','images/boat/BOAT BASSHEADS 225-2.PNG','images/boat/BOAT BASSHEADS 225-3.PNG','images/boat/BOAT BASSHEADS 225-4.PNG',1290.00,'Boat','Earbuds','The noise-cancelling microphone enables trouble free receiving of calls or undeterred sessions of musical extravaganza.Made to fit you and your lifestyle, providing a smooth grip for an extra secure and comfortable fit for your ears');
insert into products values(02,'Boat bassHeads 100','images/boat/BOAT BASSHEAD 100-1.PNG','images/boat/BOAT BASSHEAD 100-2.PNG','images/boat/BOAT BASSHEAD 100-3.PNG','images/boat/BOAT BASSHEAD 100-4.PNG',999.00,'Boat','Earbuds','The perfect way to add some style and stand out from the crowd with the boAt BassHeads 100 Hawk inspired earphones. Impedance 16Ω, Sensitivity (dB) 92db ±3db, Frequency Response 20Hz-20KHz.The stylish BassHeads 100 superior coated wired earphones are a definite fashion statement - wear your attitude with its wide variety of collection');
insert into products values(03,'Boat Rockerz 510','images/boat/boAt Rockerz 510 Wireless-1.PNG','images/boat/boAt Rockerz 510 Wireless-2.PNG','images/boat/boAt Rockerz 510 Wireless-3.PNG','images/boat/boAt Rockerz 510 Wireless-4.PNG',3990.00,'Boat','Wireless Headphones','Its 50mm drivers promises to deliver a thumping sound which you could never have imagined.Rockerz 510 promises a battery back up of upto 20 hours and a standyby time of 250 hours');
insert into products values(04,'BoAt 100 Wireless','images/boat/boAt 100 Wireless-1.PNG','images/boat/boAt 100 Wireless-2.PNG','images/boat/boAt 100 Wireless-3.PNG','images/boat/boAt 100 Wireless-4.PNG',2990.00,'Boat','Wireless Earbuds','Enjoy the instant wireless connectivity with Bluetooth v5.0 and that too with the provision of being connected to two devices simultaneously via Dual Pairing on 100 Wireless.Premium HD Sound Quality: Fill your senses with the pleasure of pure ethereal sound because the boAt 100 Wireless carries dynamic 10mm drivers that can even capture pin drop silences.');
insert into products values(05,'Sony MDR-100AAP','images/sony/Sony MDR-100AAP WIRELESS-1.PNG','images/sony/Sony MDR-100AAP WIRELESS-2.PNG','images/sony/Sony MDR-100AAP WIRELESS-3.PNG','images/sony/Sony MDR-100AAP WIRELESS-4.PNG',1299.00,'Sony','Wireless Headphones','Make your style statement with eye-catching design and colors.Enjoy the subtlest nuances of sound with high-resolution audio.Smartphone-compatible with in-line remote mic.40mm HD driver unit for dynamic range.Titanium-coated diaphragm domes minimize distortion');
insert into products values(06,'Sony MDR-ZX310AP','images/sony/Sony MDR-ZX310AP Wired-1.PNG','images/sony/Sony MDR-ZX310AP Wired-2.PNG','images/sony/Sony MDR-ZX310AP Wired-3.PNG','images/sony/Sony MDR-ZX310AP Wired-4.PNG',2190.00,'Sony','Headphones','Hands-free phone calls,Powerfull , high-quality , balanced sound,Stereo headphones');
insert into products values(07,'Sony WF-SP800N','images/sony/Sony WF-SP800N WIRELESS-1.PNG','images/sony/Sony WF-SP800N WIRELESS-2.PNG','images/sony/Sony WF-SP800N WIRELESS-3.PNG','images/sony/Sony WF-SP800N WIRELESS-4.PNG',18990.00,'Sony','Wireless Earbuds','Noise Cancellation: When you need that special playlist to take your workout to the next level, NC blocks out distractions, like the sounds of the gym or the street, so its just you and the beat.Extra Bass: WF-SP800N features EXTRA BASS for seriously powerful, punchy low-end sound.');
insert into products values(08,'PHILIPS TAE1126','images/philips/PHILIPS Audio TAE1126-1.PNG','images/philips/PHILIPS Audio TAE1126-2.PNG','images/philips/PHILIPS Audio TAE1126-3.PNG','images/philips/PHILIPS Audio TAE1126-4.PNG',690.00,'Philips','Earbuds','Perfect in-ear seal blocks out external noise.Integrated microphone & call button.3 interchangeable rubber ear caps for optimal fit in all ear.A 1.2 m long cable that is ideal for outdoor use');
insert into products values(09,'Philips SHE3700RD','images/philips/Philips SHE3700RD-1.PNG','images/philips/Philips SHE3700RD-2.PNG','images/philips/Philips SHE3700RD-3.PNG','images/philips/Philips SHE3700RD-4.PNG',399.00,'Philips','Earbuds','A high quality, glossy and colourful coating creates a sleek look while adding an extra protective surface.Acoustic system: Closed, Voice Coil: Copper, Frequency response: 11- 22 000 Hz.Cable Connection: Two-parallel, symmetric, Cable Length: 1.2 m');
insert into products values(10,'Philips TAPH802BK','images/philips/Philips TAPH802BK WIRELESS-1.PNG','images/philips/Philips TAPH802BK WIRELESS-2.PNG','images/philips/Philips TAPH802BK WIRELESS-3.PNG','images/philips/Philips TAPH802BK WIRELESS-4.PNG',4990.00,'Philips','Wireless Headphones','DESIGN: Soft ear-cups with compact flat-folding design makes these wireless headphones easy to carry..SPECIAL FEATURE: These over-ear headphones with sleek design gives excellent passive noise isolation.');
insert into products values(11,'Beats Flex Wireless','images/beats/Beats Flex Wireless-1.PNG','images/beats/Beats Flex Wireless-2.PNG','images/beats/Beats Flex Wireless-3.PNG','images/beats/Beats Flex Wireless-4.PNG',4451.00,'Beats','Wireless Earbuds','Magnetic earbuds with Auto-Play/Pause.Up to 12 hours of listening time.All-day comfort with Flex-Form cable and four eartip options.Powered by the Apple W1 headphone chip for seamless connectivity');
insert into products values(12,'Beats Ep Wired','images/beats/Beats Ep Wired-1.PNG','images/beats/Beats Ep Wired-2.PNG','images/beats/Beats Ep Wired-3.PNG','images/beats/Beats Ep Wired-4.PNG',8000.00,'Beats','Headphones','Beats EP wired on-ear headphone delivers masterfully tuned sound..Durable, lightweight design reinforced with stainless steel');

create table carts(uid varchar(15),p_id integer(4),quantity integer(2)) Foreign Key uid REFERENCES users(username);

CREATE TABLE `upwale_com`.`carts` (`user_id` VARCHAR(15) NOT NULL , `product_id` INT(4) NOT NULL , `quantity` INT(1) NOT NULL , 
Foreign key 'user_id' REFERENCES users(username) , foreign key 'product_id' REFERENCES products(id) ) ENGINE = InnoDB;